server:
  port: 9090
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecom_3
    username: root
    password: 78951
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: localhost
    port: 3999
    username: user
    password: password
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false


